services:
  db:
    image: postgres:16-alpine
    container_name: importadora-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: importadora
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - importadora_pg:/var/lib/postgresql/data

volumes:
  importadora_pg:
